server: 
  port: 8080
logging:
    level: 
        org.springframework: info
        data: DEBUG
        security: DEBUG
        org.thymeleaf: info
    config: classpath:logback-spring.xml
spring:
  mvc:
    static-path-pattern: /**
  thymeleaf: 
    servlet:
      content-type: text/html
    encoding: UTF-8
    cache: false
  datasource: 
         type: com.alibaba.druid.pool.DruidDataSource
         url: jdbc:mysql://localhost:3306/blog?&serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&useSSL=false
         username: root
         password: 12345678
         driver-class-name: com.mysql.jdbc.Driver
  #文件上传配置
  servlet:
    multipart:
      max-file-size: 10240KB
      max-request-size: 102400KB
mybatis: 
  typeAliasesPackage: com.yltrcc.blog.model.domain
  mapperLocations: classpath:mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper: 
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql